# -*- coding: utf-8 -*-
"""Esparas_MainTreeAct

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QrnX3el6oNCCMq0zFRBhF_EIWDeqJ9b1
"""

from bigtree import Node, list_to_tree

a = Node("A", data={"name": "A"})
b = Node("B", data={"name": "B"}, parent=a)
c = Node("C", data={"name": "C"}, parent=b)
d = Node("D", data={"name": "D"}, parent=b)
e = Node("E", data={"name": "E"}, parent=d)
f = Node("F", data={"name": "F"}, parent=d)
g = Node("G", data={"name": "G"}, parent=a)
h = Node("H", data={"name": "H"}, parent=g)
i = Node("I", data={"name": "I"}, parent=h)
j = Node("J", data={"name": "J"}, parent=h)
l = Node("L", data={"name": "L"}, parent=j)
k = Node("K", data={"name": "K"}, parent=h)
m = Node("M", data={"name": "M"}, parent=k)

def height(self):
    if not self.children:
        return False
    else:
        return 1 + max(child.height() for child in self.children)

Node.height = height

print("TREE: ")
a.show(attr_list=[])

print()
print("Root:" ,a.data['name'])
lea = a.leaves
print("Leaves:", [leaf.data["name"] for leaf in lea])
ans =h.ancestors
print("Ancestors of H:", [ancestors.data["name"]for ancestors in ans])
des = g.descendants
print("Descendants of G:", [descendants.data["name"] for descendants in des])
sib = i.siblings
print("Siblings of I:", [sibling.data["name"] for sibling in sib])
par = k.parent
print("Parent of K:", [par.data["name"]])
chi = d.children
print("Children of D:", [children.data["name"] for children in chi])

Node.height = height
print("Height of the tree: ", a.height())
print("Height of node G: ", g.height()-2)
print("Level of node H: ",h.depth-1)
print("Level of node A: ",a.depth-1)
print("Height of the node E: ", e.depth-1)


print("Subtrees of node H: ")
h_path = ["H/I","H/J/L", "H/K/M"]
h_root = list_to_tree(h_path)
h_root.show()