# -*- coding: utf-8 -*-
"""aesparas-finalLabExam-bcs21.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fLVbg4HhHpVXpdDXJEfGnTMdMVILezjY
"""

#!pip install bigtree
#!pip install bigtree[image]

from bigtree import Node

path_dict = {
    "1": "1",
    "1/2": "2",
    "1/2/4": "4",
    "1/2/5": "5",
    "1/3": "3",
    "1/3/6": "6",
    "1/3/6/8": "8",
    "1/3/7": "7",
    "1/3/7/9": "9"
    }

created_nodes = {"1": Node('1', data = path_dict["1"])} #format of nodes

for path, node_data in path_dict.items():
  if path != "1":
    nodes = path.split("/")
    current_node = created_nodes[nodes[0]]
    for node in nodes[1:]:
      if node not in created_nodes:
        created_nodes[node] = Node(node_data, parent = current_node, data = path_dict[path])
      current_node = created_nodes[node]

print("Binary Tree:")
created_nodes["1"].show()


#determine the horizontal distance between the vertices
class TraverseNode:
    def __init__(self, value):
        self.value = value
        self.left = None
        self.right = None

def verticalTraversal(root):
    if not root:
        return []

    horizontal_levels = {}

    def search(node, level, hd):
        if not node:
            return

        horizontal_levels.setdefault(hd, []).append((level, node.value))

        search(node.left, level + 1, hd - 1)
        search(node.right, level + 1, hd + 1)

    search(root, 0, 0)

    output = [data for hd in sorted(horizontal_levels.keys(), reverse=True) for level, data in sorted(horizontal_levels[hd])]
    return output


root = TraverseNode(1)
root.left = TraverseNode(2)
root.left.left = TraverseNode(4)
root.left.right = TraverseNode(5)
root.right = TraverseNode(3)
root.right.left = TraverseNode(6)
root.right.left.right = TraverseNode(8)
root.right.right = TraverseNode(7)
root.right.right.right = TraverseNode(9)

print(f"\nVertical Traversal (from rightmost to leftmost): {verticalTraversal(root)}")